# @package _global_

data:
  _shared_processor_configs: &shared_processor_configs
    _target_: utils.data.SVHNDataProcessor
    dirpath: dataset-files/image/svhn
    download: true
    val_fraction: 0.1
    random_state: 0

  processor:
    train:
      split: train
      <<: *shared_processor_configs
    validation:
      split: val
      <<: *shared_processor_configs
    test:
      _target_: utils.data.SVHNDataProcessor
      dirpath: dataset-files/image/svhn
      split: test
      download: true

  _shared_dataset_configs: &shared_dataset_configs
    min_nc: 5
    max_nc: 512
    # min_nq: 5
    # max_nq: 512
    use_all_queries: true

  datasets:
    train:
      _target_: utils.data.SVHNDataset
      # samples_per_epoch: 8   # For debugging
      processor: ${data.processor.train}
      <<: *shared_dataset_configs

    validation:
      _target_: utils.data.SVHNDataset
      # samples_per_epoch: 8   # For debugging
      random_state: 2025
      processor: ${data.processor.validation}
      <<: *shared_dataset_configs

    test:
      _target_: utils.data.SVHNDataset
      # samples_per_epoch: 8   # For debugging
      random_state: 2026
      processor: ${data.processor.test}
      <<: *shared_dataset_configs

  dataloaders:
    train:
      batch_size: 32
      shuffle: true
      drop_last: true
    validation:
      batch_size: 32
      shuffle: false
      drop_last: true
    test:
      batch_size: 32
      shuffle: false
      drop_last: true

plot_fn:
  _target_: utils.plot_fn.ImagePlotter
  figsize: [8.0, 3.0]
  savefig: false
  show_plots: false
  logging: true   # Will work if wandb_logging_enabled is true

params:
  x_dim: 2
  y_dim: 3

misc:
  # Experiment Naming and Organization
  experiment_name: svhn
  model_run_name: ${model_name}-seed=${.seed}

  # Logging Configuration
  wandb_logging_enabled: true   # Master toggle for W&B logging
  wandb_user: your-wandb-entity
  project: FVNP-${.experiment_name}-x=${params.x_dim}d-y=${params.y_dim}d
  name: ${.model_run_name}
  eval_name: ${.name}_eval
  hardware_callback: true       # Hardware and Performance

  # Checkpointing Configuration
  checkpointing:
    local: true
    wandb: false
    save_weights_only: true
    enable_version_counter: false
    resume_from: null
    save_last: true
    save_periodic_every_n_epochs: null
    best:
      monitor: "validation_query_loglik_epoch"
      mode: "max"
      save_top_k: 1

  default_lightning_logger: false         # Enable/disable PyTorch lightning's default local log files

  # Directory structure for local artifacts
  artifacts_dir: artifacts/${.experiment_name}/x=${params.x_dim}d_y=${params.y_dim}d/model=${model_name}/seed=${.seed}
  checkpoint_dirpath: ${.artifacts_dir}/checkpoints
  metrics_dirpath: ${.artifacts_dir}/metrics
  plots_dirpath: ${.artifacts_dir}/plots

  # Plotting Configuration
  num_plots: 6
  plot_interval: 1
  plot_fn: ${plot_fn}

  # LR Scheduler Configuration
  lr_scheduler:
    enabled: true
    t_max: ${misc.epochs}
    eta_min: 1.0e-6

  # Training Settings
  seed: 0
  epochs: 150
  check_validation_every_n_epoch: 1
  enable_progress_bar: true
  gradient_clip_val: 0.5
