# @package _global_

defaults:
  - /metrics/train: nll
  - /metrics/val: standard
  - /metrics/test: standard
  - _self_

model:
  _target_: nps.models.ACNP
  encoder: ${acnp_encoder}
  decoder: ${cnp_decoder}
  likelihood: ${likelihood}

acnp_encoder:
  _target_: nps.core.encoders.ACNPEncoder
  transformer_encoder: ${transformer_encoder}
  mha_layer: ${mha_layer}
  xy_encoder: ${xy_encoder}
  x_encoder: ${x_encoder}
  y_encoder: ${y_encoder}

transformer_encoder:
  _target_: nps.core.transformers.TransformerEncoder
  layer: ${transformer_layer}
  num_layers: ${params.num_transformer_layers}

transformer_layer:
  _target_: nps.core.attention_layers.MultiHeadAttentionLayer
  embed_dim: ${params.embed_dim}
  feedforward_dim: ${params.feedforward_dim}
  norm_first: ${params.norm_first}
  attention:
    _target_: nps.core.attentions.MultiHeadAttention
    q_dim: ${params.embed_dim}
    k_dim: ${params.embed_dim}
    v_dim: ${params.embed_dim}
    num_heads: ${params.num_heads}
    head_dim: ${params.head_dim}

mha_layer:
  _target_: nps.core.attention_layers.MultiHeadAttentionLayer
  embed_dim: ${params.embed_dim}
  feedforward_dim: ${params.feedforward_dim}
  norm_first: ${params.norm_first}
  attention:
    _target_: nps.core.attentions.MultiHeadAttention
    q_dim: ${params.embed_dim}
    k_dim: ${params.embed_dim}
    v_dim: ${params.embed_dim}
    num_heads: ${params.num_heads}
    head_dim: ${params.head_dim}

xy_encoder:
  _target_: nps.core.mlp.MLP
  in_dim: ${eval:'2 * ${params.embed_dim}'}
  out_dim: ${params.embed_dim}
  num_layers: 2
  layer_dim: ${params.embed_dim}

x_encoder:
  _target_: nps.core.mlp.MLP
  in_dim: ${params.x_dim}
  out_dim: ${params.embed_dim}
  num_layers: 2
  layer_dim: ${params.embed_dim}

y_encoder:
  _target_: nps.core.mlp.MLP
  in_dim: ${params.y_dim}
  out_dim: ${params.embed_dim}
  num_layers: 2
  layer_dim: ${params.embed_dim}

cnp_decoder:
  _target_: nps.core.decoders.ACNPDecoder
  z_decoder: ${z_decoder}

z_decoder:
  _target_: nps.core.mlp.MLP
  in_dim: ${params.embed_dim}
  out_dim: ${eval:'2 * ${params.y_dim}'}
  num_layers: ${params.num_layers}
  layer_dim: ${params.embed_dim}

likelihood:
  _target_: nps.likelihoods.gaussian.HeteroscedasticNormalLikelihood
  min_noise: 0.01
  location_transform: sigmoid
  scale_transform:
    - softplus
    - multiply:
        value: 0.99

params:
  embed_dim: 768
  num_heads: 12
  head_dim: 64
  feedforward_dim: 4096
  norm_first: true
  num_layers: 6
  num_transformer_layers: 4

model_name: ACNP-NL${params.num_layers}-NTL${params.num_transformer_layers}-EmbD${params.embed_dim}-NH${params.num_heads}xHD${params.head_dim}-FFD${params.feedforward_dim}
# model_name: ACNP

